version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8090:80"  # Port mapping from container to host
    volumes:
      - ./app:/var/www/html  # Corrected volume mapping
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: igp-db
    environment:
      MYSQL_DATABASE: igp
      MYSQL_USER: igp
      MYSQL_PASSWORD: igp
      MYSQL_ROOT_PASSWORD: igp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: